# Site settings
title: MPILAB
email: j6hickey@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.mpilab.ca" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
