# Site settings
title: MPILAB
email: j6hickey@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.mpilab.ca" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
  #- jekyll-email-protect
  #- jekyll-paginate-v2
  - jekyll/scholar
  #- jemoji
  # - bootstrap
  # - material-sass


# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------
scholar:

  last_name: Einstein

  style: apa
  locale: en

  source: /_bibliography/
  bibliography: refs.bib
  bibliography_template: bibs

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"
